feat:【账号管理】一级账号录入提供新校验接口  --story=118971366
TencentBlueKing/bk-hcm pull request #1026
Opened 2024-08-29 09:15 UTC by KooKouse

2024-10-29 06:50 UTC, chenjr15 commented on cmd/account-server/service/account-set/root-account/check.go
> +	}
一级账号不校验数量

2024-11-11 07:08 UTC, chenjr15 commented on docs/api-docs/web-server/docs/resource/account/get_account_by_secret.md
> +POST /api/v1/account/vendors/{vendor}/root_accounts/secret
```suggestion
POST /api/v1/account/vendors/{vendor}/root_accounts/get_account_by_secret
```

2024-12-10 10:06 UTC, chenjr15 commented on cmd/account-server/service/account-set/root-account/check.go
> +		return nil, fmt.Errorf("unsupported vendor: %s", vendor)
错误描述详细一些

2024-12-10 10:07 UTC, chenjr15 commented on cmd/account-server/service/account-set/root-account/check.go
> +		return nil, err
错误都补一下vendor吧

2024-12-10 11:37 UTC, chenjr15 commented on pkg/api/core/cloud/account_by_secret.go
> +type CloudProjectInfo struct {
GcpProjectInfo

2024-12-10 11:42 UTC, chenjr15 commented on cmd/account-server/service/account-set/root-account/check.go
>  	"hcm/pkg/rest"
分组

2024-12-10 11:42 UTC, chenjr15 commented on cmd/account-server/service/account-set/root-account/check.go
> +func (s *service) GetAccountBySecret(cts *rest.Contexts) (interface{}, error) {
GetRootAccountBySecret

2024-12-16 02:21 UTC, chenjr15 approved these changes

2024-12-16 07:50 UTC, chenjr15 commented
需要在cloud server application的main account  创建申请校验处增加对cloud_id的重复校验

2024-12-16 12:44 UTC, yangfan-njupt requested changes

2024-12-16 12:44 UTC, yangfan-njupt commented on cmd/account-server/service/account-set/root-account/check.go
> +		logs.Errorf("get azure account info failed, no subscription found")
日志加下 rid

2024-12-16 12:44 UTC, yangfan-njupt commented on cmd/account-server/service/account-set/root-account/check.go
> +		return nil, fmt.Errorf("failed to get application name")
加下error日志

2024-12-16 12:44 UTC, yangfan-njupt commented on cmd/account-server/service/account-set/root-account/service.go
> +	h.Add("GetRootAccountBySecret", http.MethodPost, "/vendors/{vendor}/root_accounts/get_account_by_secret",
get account接口应该用GET方法吧？

2024-12-16 12:44 UTC, yangfan-njupt commented on cmd/cloud-server/service/account/get.go
> +		return nil, fmt.Errorf("more than one subscription found: " + strings.Join(subs, ","))
1. 既然都用fmt.Errorf了，就用格式化的方式拼装结果吧，"more than one subscription found: %s"
2. 记录下error日志

2024-12-16 12:44 UTC, yangfan-njupt commented on cmd/cloud-server/service/account/get.go
> +		return nil, fmt.Errorf("failed to get application name")
同上，补充下日志

2024-12-16 12:44 UTC, yangfan-njupt commented on cmd/cloud-server/service/account/get.go
> +		return nil, fmt.Errorf("more than one project found:" + strings.Join(projects, ","))
同上

2024-12-16 12:44 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/account/get_account_by_secret.md
> +| Email                      | string | 邮箱地址    |
```suggestion
| email                      | string | 邮箱地址    |
```

2024-12-17 02:13 UTC, KooKouse commented on cmd/account-server/service/account-set/root-account/service.go
> +	h.Add("GetRootAccountBySecret", http.MethodPost, "/vendors/{vendor}/root_accounts/get_account_by_secret",
但是里面又带有request body....

2024-12-19 06:12 UTC, fxdgg commented on cmd/account-server/service/account-set/root-account/check.go
> +	default:
目前不支持tcloud是吧？

2024-12-19 06:14 UTC, fxdgg commented on cmd/hc-service/service/account/check.go
> +			projectInfo = info
匹配到之后break一下好一点

2024-12-19 06:15 UTC, fxdgg commented on cmd/hc-service/service/account/check.go
> +			curSubscription = subscription
同上

2024-12-19 06:17 UTC, KooKouse commented on cmd/account-server/service/account-set/root-account/check.go
> +	default:
目前云账号功能没有支持腾讯云

2024-12-20 06:55 UTC, chenjr15 commented on cmd/account-server/service/account-set/root-account/service.go
> +	h.Add("GetRootAccountBySecret", http.MethodPost, "/vendors/{vendor}/root_accounts/get_account_by_secret",
改query吧

2025-01-03 07:16 UTC, chenjr15 approved these changes

2025-01-07 04:02 UTC, yangfan-njupt approved these changes

2025-01-07 06:24 UTC, merged