feat: 查询云上镜像列表接口 --story=120253951
TencentBlueKing/bk-hcm pull request #1122
Opened 2024-10-22 07:28 UTC by KooKouse

2024-10-24 07:18 UTC, chenjr15 commented on pkg/criteria/enumor/image.go
> +)
命名加一下TCloud 前缀

2024-10-24 07:19 UTC, chenjr15 commented on cmd/cloud-server/service/image/tcloud.go
> +}
需要补充鉴权，这个每个账号权限不一样

2024-10-24 07:20 UTC, chenjr15 commented on cmd/cloud-server/service/image/init.go
> +
```suggestion
	h.Add("TCLoudListImage", http.MethodPost, "/vendors/tcloud/images/query_from_cloud", svc.TCLoudListImage)

```

2024-10-28 03:04 UTC, chenjr15 commented on cmd/cloud-server/service/image/init.go
> +	h.Add("TCLoudBizListImage", http.MethodPost, "/bizs/{bk_biz_id}/vendors/tcloud/images/query_from_cloud",
TCLoudListImage -> TCloudQueryImage

2024-10-28 03:07 UTC, chenjr15 commented on docs/api-docs/web-server/docs/biz/image/list_tcloud_image.md
> +- 该接口功能描述：查询腾讯云镜像列表。
业务访问

2024-10-28 03:09 UTC, chenjr15 commented on cmd/cloud-server/service/image/tcloud.go
> +	return svc.tcloudListImage(cts.Kit, req)
这个好像没鉴业务下访问权限，参考一下其他资源业务下鉴权，用那个统一的handler

2024-10-28 03:19 UTC, KooKouse commented on cmd/cloud-server/service/image/tcloud.go
> +	return svc.tcloudListImage(cts.Kit, req)
业务下接口：按业务鉴权，不管是哪个账号，只要业务能选到账号，就能查到该账号的镜像 
账号下接口：按账号鉴权

应该是在已有的校验逻辑里面再加一个业务访问的权限校验逻辑对吧？之前理解了 《不管是哪个账号，只要业务能选到账号，就能查到该账号的镜像 》

2024-10-28 09:44 UTC, chenjr15 commented on cmd/auth-server/service/auth/gen_id.go
> +	default:
应该是 AccountFind

2024-10-28 09:45 UTC, chenjr15 requested changes
漏了补充业务下账号权限

2024-10-29 02:18 UTC, chenjr15 commented on cmd/cloud-server/service/account/rel.go
> +		Action: meta.Find})
改alias的 pr 好像 漏掉了这个接口

2024-10-30 02:28 UTC, KooKouse commented on cmd/cloud-server/service/account/rel.go
> +		Action: meta.Find})
![image](https://github.com/user-attachments/assets/82a5a226-ef26-4d3d-bd62-fdabe7c95d71)
看起来应该不用修改吧？

2024-11-06 07:05 UTC, fxdgg commented on cmd/cloud-server/service/image/init.go
> +	h.Add("TCLoudBizListImage", http.MethodPost, "/bizs/{bk_biz_id}/vendors/tcloud/images/query_from_cloud",
"TCLoudBizListImage"是不是也得统一改成“TCLoudBizQueryImage”?

2024-11-06 07:08 UTC, fxdgg commented on docs/api-docs/web-server/docs/biz/image/list_tcloud_image.md
> +| Name   | string       | 是  | 过滤条件 |
这里的“Name”建议改成小写的“name”

2024-11-06 07:09 UTC, fxdgg commented on docs/api-docs/web-server/docs/resource/image/list_tcloud_image.md
> +| Name   | string       | 是  | 过滤条件 |
同上

2024-11-06 07:11 UTC, fxdgg commented on pkg/client/hc-service/tcloud/image.go
> +	typesimage "hcm/pkg/adaptor/types/image"
导入顺序错误

2024-11-06 07:11 UTC, fxdgg commented on pkg/client/hc-service/tcloud/image.go
> +	"hcm/pkg/kit"
同上

2024-11-07 06:45 UTC, chenjr15 submitted a review, later dismissed

2024-11-07 07:00 UTC, fxdgg commented on cmd/hc-service/service/image/tcloud.go
> +package image
缺少文件头

2024-11-08 02:32 UTC, fxdgg approved these changes

2024-11-10 15:43 UTC, merged