feat: 支持同步clb标签
TencentBlueKing/bk-hcm pull request #1149
Opened 2024-11-01 04:22 UTC by chenjr15

2024-11-01 09:13 UTC, yangfan-njupt requested changes

2024-11-01 09:25 UTC, chenjr15 commented on cmd/hc-service/service/sync/tcloud/load_balancer.go
> +		return hd.request.CloudIDs, nil
不一定。在这个情况里，返回一个不存在的id也没关系，因为这里没有对hd.lbCache赋值，所以后续会按id去云上查一次数据。
对于指定的id是云上不存在而本地还有的，需要会在后续同步过程中把本地删除（预期内）

2024-11-13 02:14 UTC, yangfan-njupt approved these changes

2024-11-14 12:46 UTC, zouxingyuks approved these changes

2024-11-14 12:46 UTC, zouxingyuks commented on pkg/adaptor/tcloud/clb.go
> +			Name:   cvt.ValToPtr("tag:" + k),
能不能做成函数，比如 k.Name() ?

2024-11-14 12:46 UTC, zouxingyuks commented on pkg/runtime/filter/expression_test.go
> +			t.Errorf("validate field failed, err: %v", err)
特定错误请定义为常量/变量

2024-11-14 12:46 UTC, zouxingyuks commented on pkg/runtime/filter/expression.go
> +	if dotIdx == -1 {
magicNum 请定义为常量

2024-11-14 12:57 UTC, fxdgg approved these changes

2024-11-14 13:37 UTC, ZQHcode commented on cmd/cloud-server/service/account/sync.go
> +		found = true
到这可以break了

2024-11-14 13:37 UTC, ZQHcode commented on cmd/cloud-server/service/account/sync.go
> +	return "started", err
```suggestion
	return "started", nil
```

2024-11-14 13:37 UTC, ZQHcode commented on cmd/cloud-server/service/account/sync.go
> +		if err != nil {
err没打印

2024-11-15 01:32 UTC, chenjr15 commented on cmd/cloud-server/service/account/service.go
> +		"/vendors/{vendor}/accounts/{account_id}/resources/{res}/sync_by_cond", svc.SyncCloudResourceByCond)
已经先合入了

2024-11-15 02:02 UTC, chenjr15 commented on pkg/runtime/filter/expression_test.go
> +			t.Errorf("validate field failed, err: %v", err)
这个是测试文件，基本不会用到第二次了呀

2024-11-15 04:10 UTC, chenjr15 commented on cmd/hc-service/logics/res-sync/tcloud/load_balancer.go
> +		rules = append(rules, tools.RuleJsonIn("tags."+k, params.TagFilters[k]))
fmt.Sprintf性能不如直接拼接字符串的

2024-11-15 04:10 UTC, chenjr15 commented on pkg/adaptor/tcloud/clb.go
> +			Name:   cvt.ValToPtr("tag:" + k),
这个是纯string，可以写成函数

2024-11-15 07:08 UTC, ZQHcode approved these changes

2024-11-15 07:41 UTC, merged