feat: tcloud 安全组创建支持打标签
TencentBlueKing/bk-hcm pull request #1186
Opened 2024-11-28 03:50 UTC by chenjr15

--story=120959481 腾讯云安全组创建支持打标签

2024-12-05 02:53 UTC, KooKouse approved these changes

2024-12-05 08:49 UTC, yangfan-njupt requested changes

2024-12-05 08:49 UTC, yangfan-njupt commented on cmd/hc-service/service/security-group/tcloud_security_group.go
> +			err, opt, cts.Kit.Rid)
这里打印的是地址，用 *opt

2024-12-06 01:55 UTC, yangfan-njupt approved these changes

2024-12-09 10:07 UTC, merged