feat: 查询主机关联的安全组规则接口 --story=121049185
TencentBlueKing/bk-hcm pull request #1194
Opened 2024-12-05 02:41 UTC by KooKouse

2024-12-05 09:40 UTC, yangfan-njupt requested changes

2024-12-05 09:40 UTC, yangfan-njupt commented on cmd/cloud-server/service/cvm/security_group_rule.go
> +func (svc *cvmSvc) GetCvmSecurityGroupRules(cts *rest.Contexts) (interface{}, error) {
ListCvmSecurityGroupRules

2024-12-05 09:40 UTC, yangfan-njupt commented on cmd/cloud-server/service/cvm/security_group_rule.go
> +func (svc *cvmSvc) getCvmSecurityGroupRules(kt *kit.Kit, vendor enumor.Vendor, cvmID, sgID string, req *core.ListReq) (
listCvmSecurityGroupRules

2024-12-05 09:40 UTC, yangfan-njupt commented on cmd/cloud-server/service/cvm/security_group_rule.go
> +		return fmt.Errorf("cvm and security group relation not found, cvm_id: %s, security_group_id: %s", cvmID, sgID)
加下error日志吧

2024-12-05 09:40 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/biz/cvm/get_cvm_security_group_rules.md
> +| type | string | 规则类型。（枚举值：egress、ingress） |
这个是哪来的

2024-12-05 09:40 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/biz/cvm/get_cvm_security_group_rules.md
> +  "page": {
这个示例不对吧，除了page，其他参数全部都没带

2024-12-05 09:40 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/biz/cvm/get_cvm_security_group_rules.md
> +  "page": {
同上

2024-12-05 09:40 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/biz/cvm/get_cvm_security_group_rules.md
> +| details | array  | 查询返回的数据        |
```suggestion
| details | array  object | 查询返回的数据        |
```

2024-12-05 10:07 UTC, KooKouse commented on docs/api-docs/web-server/docs/biz/cvm/get_cvm_security_group_rules.md
> +| type | string | 规则类型。（枚举值：egress、ingress） |
docs/api-docs/web-server/docs/biz/security-group/list_aws_security_group_rule.md:99

老文档直接copy....

2024-12-05 10:07 UTC, KooKouse commented on docs/api-docs/web-server/docs/biz/cvm/get_cvm_security_group_rules.md
> +  "page": {
已补充

2024-12-06 02:02 UTC, yangfan-njupt approved these changes

2024-12-09 12:07 UTC, chenjr15 approved these changes

2024-12-09 12:07 UTC, merged