fix: 修复 etcd keepAlive 无法及时关闭 content
TencentBlueKing/bk-hcm pull request #1214
Opened 2024-12-11 08:43 UTC by zouxingyuks

2024-12-11 09:11 UTC, yangfan-njupt requested changes

2024-12-11 09:11 UTC, yangfan-njupt commented on pkg/serviced/service.go
> +// grantLeaseEtcd put kv with lease, if the lease is 0, need to grant lease and put kv with lease.
注释不太对哈

2024-12-11 09:11 UTC, yangfan-njupt commented on pkg/serviced/service.go
> +// RenewLease judge if the service key exists, if not exist, need to re-register.
同上，注释和方法的功能不一致

2024-12-11 09:11 UTC, yangfan-njupt commented on pkg/serviced/service.go
> +	return true
建议返回error

2024-12-11 11:33 UTC, zouxingyuks commented on pkg/serviced/service.go
> +// RenewLease judge if the service key exists, if not exist, need to re-register.
adjust

2024-12-11 11:33 UTC, zouxingyuks commented on pkg/serviced/service.go
> +// grantLeaseEtcd put kv with lease, if the lease is 0, need to grant lease and put kv with lease.
adjust

2024-12-11 11:54 UTC, yangfan-njupt approved these changes

2024-12-12 02:27 UTC, zouxingyuks commented on pkg/serviced/service.go
> +	return true
fixed

2025-01-07 07:34 UTC, yangfan-njupt approved these changes

2025-01-14 07:29 UTC, chenjr15 commented on pkg/serviced/service.go
> +	}
这里没设置超时

2025-01-14 07:30 UTC, chenjr15 commented on pkg/serviced/service.go
> +	}
另外在调用keepalive之前会第一次grant lease 也没有配置超时

2025-02-05 09:17 UTC, closed without merging