feat： 全局配置规范性修正
TencentBlueKing/bk-hcm pull request #1215
Opened 2024-12-11 09:35 UTC by zouxingyuks

2024-12-25 12:49 UTC, chenjr15 approved these changes

2025-01-03 02:11 UTC, yangfan-njupt requested changes

2025-01-03 02:11 UTC, yangfan-njupt commented on pkg/tools/util/conv.go
> +		return fmt.Sprintf("%d", a)
这个和 %v 不是等价的么，这个拆分和原版的区别是？

2025-01-03 02:11 UTC, yangfan-njupt commented on pkg/tools/util/conv.go
> +		return fmt.Sprintf("%v", a)
switch需要default

2025-01-08 06:18 UTC, yangfan-njupt approved these changes

2025-01-08 06:21 UTC, merged