GitHub/fix account api permission
TencentBlueKing/bk-hcm pull request #1218
Opened 2024-12-16 03:09 UTC by KooKouse

2025-01-03 09:45 UTC, fxdgg commented on cmd/account-server/service/account-set/root-account/add.go
> +			Extension:   &dataproto.GcpRootAccountExtensionCreateReq{},
上面的extension不用赋值到这里吗？

2025-01-03 09:51 UTC, fxdgg commented on docs/api-docs/web-server/docs/resource/account/add_root_account.md.md
> +- 该接口提供版本：v1.6.0+。
版本号需要确认下改成最新的了

2025-01-03 09:52 UTC, fxdgg commented on docs/api-docs/web-server/docs/resource/account/add_root_account.md.md
> +| bak_managers | string | 是  | 备份负责人  |
确认下这俩负责人字段，不是数组类型吗？

2025-01-03 09:57 UTC, fxdgg commented on docs/api-docs/web-server/docs/resource/bill/delete_adjustment_item.md
> +| ids  | string array | 是  | 调账明细列表 |
有最大数量限制吗？

2025-01-03 09:58 UTC, fxdgg commented on docs/api-docs/web-server/docs/resource/bill/create_adjustment_item.md
> +| items           | adjustment_item array | 是  | 调账明细列表  |
items是否有数量限制？

2025-01-06 02:04 UTC, KooKouse commented on docs/api-docs/web-server/docs/resource/account/add_root_account.md.md
> +- 该接口提供版本：v1.6.0+。
应该不需要吧？这些接口应该已经在v1.6.0提供了？现在只是补全接口文档

2025-01-06 02:07 UTC, KooKouse commented on docs/api-docs/web-server/docs/resource/bill/delete_adjustment_item.md
> +| ids  | string array | 是  | 调账明细列表 |
pkg/api/account-server/bill/billitem.go:181

req声明中没有说明，delete Filter会有隐藏逻辑吗

2025-01-07 06:49 UTC, yangfan-njupt requested changes

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/account/get_root_account.md
> +| account_id | 是    | string | 二级账号ID |
获取一级账号的接口，为啥参数要传二级账号ID？

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/account/get_main_account.md.md
> +| account_id | string | 是  | 二级账号ID。 |
url里已经有account_id了，body里还需要么？

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/account/update_root_account.md
> +| account_id   | 是    | string       | 二级账号ID          |
同上，修改一级账号为啥要传二级账号ID

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/bill/confirm_root_account_summarys.md
> +- 该接口所需权限：
不需要权限吗？还是漏写了？不需要鉴权的话填下“无”吧

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/bill/reaccount_root_account_summarys.md
> +- 该接口所需权限：
同上，这个接口不需要鉴权吗

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/bill/sum_main_account_summarys.md
> +- 该接口所需权限：
同上，权限

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/create_application_for_create_main_account.md
> +- 该接口所需权限：
同上，权限

2025-01-07 06:49 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/complete_application_for_create_main_account.md
> +- 该接口功能描述：单据信息填写。
单据信息填写也需要后端介入么？什么的单据？有点没明白这个接口的作用

2025-01-07 09:54 UTC, KooKouse commented on docs/api-docs/web-server/docs/resource/complete_application_for_create_main_account.md
> +- 该接口功能描述：单据信息填写。
其实，我也没看懂这个接口... https://iwiki.woa.com/p/4010726996

2025-01-07 11:26 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/complete_application_for_create_main_account.md
> +- 该接口功能描述：单据信息填写。
emmm好吧

2025-01-07 11:29 UTC, yangfan-njupt requested changes

2025-01-07 11:29 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/account/get_root_account.md
> +| account_id | 是    | string | 二级账号ID |
描述改下，这里应该是一级账号ID吧？

2025-01-07 11:29 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/account/update_root_account.md
> +| account_id   | 是    | string       | 二级账号ID          |
同上，一级账号ID

2025-01-08 04:01 UTC, yangfan-njupt approved these changes

2025-02-20 02:27 UTC, chenjr15 submitted a review, later dismissed

2025-02-26 03:17 UTC, yangfan-njupt approved these changes

2025-02-26 03:26 UTC, chenjr15 commented on docs/api-docs/web-server/docs/resource/bill/delete_adjustment_item.md
> +| ids  | string array | 是  | 调账明细列表 |
in 默认会限500

2025-02-26 03:26 UTC, chenjr15 commented on docs/api-docs/web-server/docs/resource/bill/delete_adjustment_item.md
> +| ids  | string array | 是  | 调账明细列表 |
后续pr补充

2025-02-26 03:27 UTC, merged