feat: 主机-批量绑定安全组 --story=121269846
TencentBlueKing/bk-hcm pull request #1222
Opened 2024-12-25 08:45 UTC by KooKouse

2025-01-06 13:26 UTC, yangfan-njupt requested changes

2025-01-06 13:26 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/cvm/cvm_batch_associate_security_groups.md
> +- 该接口所需权限：业务-IaaS资源操作。
这个和业务用的接口权限应该不一样吧？

2025-01-06 13:26 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/biz/cvm/cvm_batch_associate_security_groups.md
> +| bk_biz_id          | int64        | 是  | 业务ID                                |
url已经带了biz_id和cvm_id，这里可以不带了

2025-01-06 13:26 UTC, yangfan-njupt commented on docs/api-docs/web-server/docs/resource/cvm/cvm_batch_associate_security_groups.md
> +| cvm_id             | string       | 是  | 主机ID                                |
url已经带了cvm_id，这里可以不带了

2025-01-06 13:26 UTC, yangfan-njupt commented on pkg/adaptor/aws/cvm.go
> +	client, err := a.clientSet.ec2Client(opt.Region)
这里也判断下opt是否为nil吧，以及Validate

2025-01-07 01:18 UTC, KooKouse commented on cmd/hc-service/service/cvm/aws.go
> +		logs.Errorf("batch associate security group failed, err: %v, opt: %v, rid: %s", err, opt, cts.Kit.Rid)
%v打印的是指针指向的值，其实不会直接打印地址...

2025-01-07 01:49 UTC, KooKouse commented on docs/api-docs/web-server/docs/biz/cvm/cvm_batch_associate_security_groups.md
> +| bk_biz_id          | int64        | 是  | 业务ID                                |
之前的接口文档写法都是这样子...path variable也会放在这里

2025-01-07 07:10 UTC, yangfan-njupt commented on cmd/hc-service/service/cvm/aws.go
> +		logs.Errorf("batch associate security group failed, err: %v, opt: %v, rid: %s", err, opt, cts.Kit.Rid)
@KooKouse OK，你把这个对话关掉吧，以及下边两个接口文档参数的comment，我暂时没权限

2025-01-07 11:36 UTC, chenjr15 commented on cmd/hc-service/service/cvm/aws.go
> +		logs.Errorf("request dataservice create security group cvm rels failed, err: %v, req: %+v, rid: %s",
绑定接口是批量替换，可重入，错误暴露给用户直接重试即可

2025-01-07 11:56 UTC, yangfan-njupt approved these changes

2025-01-07 12:01 UTC, ZQHcode commented on docs/api-docs/web-server/docs/biz/cvm/cvm_batch_associate_security_groups.md
> +| security_group_ids | string array | 是  | 安全组ID, 前端排序后的安全组顺序, 云上接口会根据这个顺序覆盖更新 |
security_group_ids的数量限制可以写下

2025-01-07 12:01 UTC, ZQHcode commented on docs/api-docs/web-server/docs/resource/cvm/cvm_batch_associate_security_groups.md
> +| security_group_ids | string array | 是  | 安全组ID, 前端排序后的安全组顺序, 云上接口会根据这个顺序覆盖更新 |
同上

2025-01-08 01:37 UTC, KooKouse commented on cmd/cloud-server/service/cvm/batch_associate.go
> +
validate方法中已有相关逻辑

2025-01-08 03:59 UTC, yangfan-njupt approved these changes

2025-01-08 06:20 UTC, merged