fix: 创建监听器时缺少健康检查参数 --story=121131936
TencentBlueKing/bk-hcm pull request #1227
Opened 2024-12-27 09:55 UTC by KooKouse

2025-01-03 07:20 UTC, chenjr15 commented on cmd/cloud-server/logics/load-balancer/create_layer4_listener_executor.go
> +				req.HealthCheck.HealthSwitch = converter.ValToPtr(int64(1))
else req.HealthCheck.HealthSwitch = converter.ValToPtr(int64(0))

2025-01-06 08:18 UTC, yangfan-njupt requested changes

2025-01-06 08:18 UTC, yangfan-njupt commented on cmd/hc-service/service/load-balancer/tcloud.go
> +	if req.Protocol.IsLayer4Protocol() {
这里4层的逻辑和下边7层的逻辑看起来是一样的，能不能合并？

2025-01-06 08:23 UTC, KooKouse commented on cmd/hc-service/service/load-balancer/tcloud.go
> +	if req.Protocol.IsLayer4Protocol() {
// HealthCheck 健康检查相关参数，此参数仅适用于TCP/UDP/TCP_SSL/QUIC监听器
pkg/adaptor/types/load-balancer/tcloud.go:445

下面七层的逻辑是 URLRule 的健康检查，不是同一个healthCheck参数~

2025-01-07 11:30 UTC, yangfan-njupt requested changes

2025-01-08 02:06 UTC, chenjr15 approved these changes

2025-01-08 03:58 UTC, yangfan-njupt approved these changes

2025-01-08 06:21 UTC, merged