feat(target_group): 新增目标组创建、更新、删除、列表、详情接口
TencentBlueKing/bk-hcm pull request #640
Opened 2024-03-15 02:12 UTC by fxdgg

--story=116325110

2024-03-16 01:55 UTC, chenjr15 requested changes
需要修改后重新rebase目标分支

2024-03-16 01:55 UTC, chenjr15 commented on cmd/cloud-server/service/load-balancer/target_group.go
> +	if err != nil {
`ResType: meta.LoadBalancer` 应该是目标组？

2024-03-16 01:55 UTC, chenjr15 commented on cmd/cloud-server/service/load-balancer/target_group.go
> +	}
没有处理count==true的情况

2024-03-16 01:55 UTC, chenjr15 commented on cmd/cloud-server/service/load-balancer/target_group.go
> +			},
这个可以用tools.ContainerExpression或者考虑新写的 tools.RuleXX  和 ExpressAnd代替

2024-03-16 01:55 UTC, chenjr15 commented on cmd/cloud-server/service/load-balancer/target_group.go
> +}
这个函数有人调用吗

2024-03-16 01:55 UTC, chenjr15 commented on cmd/cloud-server/service/load-balancer/update.go
> +}
这里更新看起来直接透传到了dataservice， 写个todo 标注一下后面如果碰到健康检查需要修改对应监听器

2024-03-16 01:55 UTC, chenjr15 commented on pkg/dal/dao/cloud/clb/load_balancer_target_group.go
>  	[]string, error) {
创建目标组没有审计，创建的审计是写在DAO里的

2024-03-16 01:55 UTC, chenjr15 commented on cmd/data-service/service/cloud/load-balancer/create.go
> +		}
这个判断CloudVpcID是为什么呢

2024-03-16 01:55 UTC, chenjr15 commented on cmd/data-service/service/cloud/load-balancer/update.go
> +			}
不ok是啥情况，需要报错吗

2024-03-16 01:55 UTC, chenjr15 commented on pkg/api/data-service/cloud/target_group.go
> +
这几个似乎没有人调用，用公共结构体就行了

2024-03-16 01:55 UTC, chenjr15 commented on pkg/api/data-service/cloud/target_group.go
> +}
好像没人调用

2024-03-16 01:55 UTC, chenjr15 commented on scripts/sql/9999_tcloud_clb.sql
> +    `extension`         json         not null,
default '{}'

2024-03-16 02:38 UTC, fxdgg commented on scripts/sql/9999_tcloud_clb.sql
> +    `extension`         json         not null,
已优化

2024-03-16 02:38 UTC, fxdgg commented on pkg/api/data-service/cloud/target_group.go
> +}
已删除

2024-03-16 02:39 UTC, fxdgg commented on pkg/api/data-service/cloud/target_group.go
> +
已删除

2024-03-16 02:39 UTC, fxdgg commented on cmd/data-service/service/cloud/load-balancer/update.go
> +			}
已增加报错

2024-03-16 02:39 UTC, fxdgg commented on cmd/data-service/service/cloud/load-balancer/create.go
> +		}
已优化

2024-03-16 02:39 UTC, fxdgg commented on pkg/dal/dao/cloud/clb/load_balancer_target_group.go
>  	[]string, error) {
已增加审计

2024-03-16 02:59 UTC, fxdgg commented on cmd/cloud-server/service/load-balancer/target_group.go
> +	if err != nil {
已优化

2024-03-16 02:59 UTC, fxdgg commented on cmd/cloud-server/service/load-balancer/target_group.go
> +			},
已优化

2024-03-16 02:59 UTC, fxdgg commented on cmd/cloud-server/service/load-balancer/update.go
> +}
已添加todo

2024-03-16 03:02 UTC, fxdgg commented on cmd/cloud-server/service/load-balancer/target_group.go
> +}
有调用的地方，如：listLbUrlRule

2024-03-16 04:40 UTC, fxdgg commented on cmd/cloud-server/service/load-balancer/target_group.go
> +	}
已处理

2024-03-18 01:43 UTC, chenjr15 approved these changes

2024-03-18 01:44 UTC, merged