feat: 增加对异步请求云接口的限流重试支持 story=117465236
TencentBlueKing/bk-hcm pull request #863
Opened 2024-06-05 11:52 UTC by Kickflip73

- 海垒请求云接口限流需求

2024-06-05 11:52 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-hcm?pullRequest=863) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-hcm?pullRequest=863) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-hcm?pullRequest=863) it.</sub>

2024-06-05 12:01 UTC, chenjr15 commented on cmd/hc-service/logics/cloud-adaptor/cloud_client.go
> +	return client, err
这一个先不加吧

2024-06-05 12:02 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +		interval := time.Duration(randomSec) * time.Millisecond
randomSec 没有秒的意思吧

2024-06-05 12:06 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +		maxRetries := 1000
方法名改成SetXXX吧，一般WithXXX应该返回一个新实例 

另外里面可以考虑 写成
```go
if !retryable{
    return
}

```

2024-06-05 12:06 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +		maxRetryInterval := 500
这几个应该写成配置，至少应该写成常量

2024-06-05 12:10 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +func (t *TCloudImpl) WithRateLimitExceededRetryable(retryable bool) {
方法名应该在明确一点，这个函数应该是随机设定一个固定的重试时间，然后对可以重试的接口自动重试。这里怎么判断能否重试有确定吗？还是所有接口都会重试？

2024-06-05 12:29 UTC, Kickflip73 commented on pkg/adaptor/tcloud/tcloud.go
> +		interval := time.Duration(randomSec) * time.Millisecond
这个变量名写错了

2024-06-05 12:45 UTC, Kickflip73 commented on pkg/adaptor/tcloud/tcloud.go
> +		maxRetries := 1000
已修改

2024-06-05 12:45 UTC, Kickflip73 commented on pkg/adaptor/tcloud/tcloud.go
> +		maxRetryInterval := 500
已换成常量

2024-06-06 02:04 UTC, breezelxp requested changes

2024-06-06 02:04 UTC, breezelxp commented on pkg/adaptor/tcloud/client.go
> +
这似乎不符合预期吧，说的是重试时间随机，不是重试次数随机，这里边的差别大了去了吧？

2024-06-06 02:10 UTC, Kickflip73 commented on pkg/adaptor/tcloud/client.go
> +
这里的逻辑就是设置传入进来的随机重试时间，重试次数是固定的

2024-06-06 02:10 UTC, chenjr15 commented on pkg/adaptor/tcloud/client.go
> +	"time"
import 需要分组： 

1. golang 内部包
2. hcm包
3. 第三方包

2024-06-06 02:14 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +	"time"
存量代码的问题也一起改一下吧
分组： 

1. golang 内部包
2. hcm包
3. 第三方包

2024-06-06 02:23 UTC, Kickflip73 commented on pkg/adaptor/tcloud/tcloud.go
> +	randomNum := rand.Intn(constant.MaxRetryInterval-constant.MinRetryInterval+1) + constant.MinRetryInterval
已经找到并修改了

2024-06-06 02:24 UTC, Kickflip73 commented on pkg/adaptor/tcloud/interface.go
> +	SetRateLimitExceededRetryable(retryable bool)
已修改为retry

2024-06-06 02:25 UTC, Kickflip73 commented on cmd/hc-service/logics/cloud-adaptor/cloud_client.go
> +	return client, err
已经去掉

2024-06-06 02:40 UTC, Kickflip73 commented on pkg/adaptor/tcloud/tcloud.go
> +	"time"
已经调整顺序了

2024-06-06 06:55 UTC, fxdgg commented on pkg/adaptor/tcloud/client.go
> +	SetRateLimitExceededRetryWithConstantInterval(int, time.Duration)
给入参加上参数名吧，方便理解

2024-06-06 06:59 UTC, fxdgg commented on pkg/criteria/constant/rate_limit_retry.go
> +	MaxRetries = 1000
需要重试这么多次嘛？建议评估一个合理点的次数，结合重试毫秒时间

2024-06-06 06:59 UTC, fxdgg commented on pkg/criteria/constant/rate_limit_retry.go
> +package constant
1、需要加上TencentBlueKing的Copyright描述
2、package需要有注释

2024-06-06 07:00 UTC, fxdgg commented on pkg/adaptor/tcloud/interface.go
> +	SetRateLimitExceededRetryWithRandomInterval(retryable bool)
名称过长， 看看能否简化下呢？

2024-06-06 07:02 UTC, fxdgg commented on pkg/adaptor/tcloud/client.go
>  package tcloud
1、缺少了Copyright描述
2、package缺少了对于包名的注释说明

2024-06-06 09:22 UTC, Kickflip73 commented on pkg/criteria/constant/rate_limit_retry.go
> +package constant
已加上注释

2024-06-06 09:31 UTC, Kickflip73 commented on pkg/adaptor/tcloud/client.go
>  package tcloud
1. 已加上
2. 已修改

2024-06-06 09:32 UTC, Kickflip73 commented on pkg/adaptor/tcloud/interface.go
> +	SetRateLimitExceededRetryWithRandomInterval(retryable bool)
已简化为：SetRateLimitRetryWithConstInterval

2024-08-05 12:25 UTC, fxdgg commented on pkg/adaptor/tcloud/interface.go
> +	SetRateLimitExceededRetryable(retryable bool)
参数名retryable，我看还没修改呢

2024-08-16 02:14 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +}
这个实现是随机确定了一个重试时间，然后就固定重试一千次？似乎不符合预期吧

2024-08-16 02:15 UTC, chenjr15 commented on pkg/adaptor/tcloud/tcloud.go
> +}
1. 重试时间确定以后就固定了是否合理
2. 固定重试一千次是否合理

2024-08-19 12:10 UTC, chenjr15 commented on pkg/criteria/constant/rate_limit_retry.go
> +	MaxRetries = 1000
限流竞争激烈应该降低请求次数避免拥挤

2024-08-19 12:44 UTC, Kickflip73 commented on pkg/adaptor/tcloud/tcloud.go
> +}
1.已修改重试时间为每次都随机
2.重试次数已减少为300

2024-08-19 12:45 UTC, Kickflip73 commented on pkg/adaptor/tcloud/interface.go
> +	SetRateLimitExceededRetryable(retryable bool)
已修改

2024-08-19 12:45 UTC, Kickflip73 commented on pkg/criteria/constant/rate_limit_retry.go
> +	MaxRetries = 1000
已减少到300次

2024-08-19 12:56 UTC, chenjr15 approved these changes

2024-08-20 06:27 UTC, ZQHcode approved these changes

2024-08-20 08:32 UTC, merged