feat: 账单明细查询接口
TencentBlueKing/bk-hcm pull request #876
Opened 2024-06-14 12:01 UTC by chenjr15

--story=118018475

2024-06-14 13:12 UTC, abstractmj commented on pkg/client/data-service/huawei/client.go
> + * an "AS IS" BASIS, WITHOUT 	h.Add("ListBillItemExt", http.MethodPost, "/vendors/{vendor}/bills/items/list", svc.ListBillItemExt)
error comment

2024-06-14 13:14 UTC, liuchenyiwork requested changes

2024-06-14 13:14 UTC, liuchenyiwork commented on pkg/client/data-service/tcloud/bill.go
本期功能不支持tcloud的话，是否先不提供该部分功能的client？

2024-06-14 13:14 UTC, liuchenyiwork commented on cmd/data-service/service/bill/billitem/create.go
> +	case enumor.TCloud:
TCloud不支持账单功能的话是不是先不加，应该是unsupport vendor

2024-06-14 13:14 UTC, liuchenyiwork commented on cmd/data-service/service/bill/billitem/create.go
> +	case enumor.TCloud:
下同

2024-06-14 13:14 UTC, liuchenyiwork commented on pkg/adaptor/huawei/bill.go
> +		logs.Errorf("huawei fee record list request adaptor failed, err: %+v, opt: %+v, rid: %s", opt, err, kt.Rid)
err和opt的顺序与对应占位符顺序不一致

2024-06-15 03:17 UTC, chenjr15 commented on pkg/client/data-service/huawei/client.go
> + * an "AS IS" BASIS, WITHOUT 	h.Add("ListBillItemExt", http.MethodPost, "/vendors/{vendor}/bills/items/list", svc.ListBillItemExt)
已修复

2024-06-15 03:17 UTC, chenjr15 commented on cmd/data-service/service/bill/billitem/update.go
> +			logs.Errorf("failt ot update bill item for %s, err: %v, rid: %s", billItem.ID, err, cts.Kit.Rid)
已修复

2024-06-15 03:18 UTC, chenjr15 commented on pkg/client/data-service/tcloud/bill.go
已删除

2024-06-15 03:38 UTC, liuchenyiwork commented
LGTM

2024-06-15 03:39 UTC, liuchenyiwork approved these changes
LGTM

2024-06-15 04:35 UTC, fxdgg commented on cmd/account-server/service/bill/billitem/bill_items.go
> +	_, err := b.client.DataService().Zenlayer.Bill.ListBillItem(kt, billListReq)
导出华为账单，这里不应该是Zenlayer吧？

2024-06-15 04:39 UTC, fxdgg commented on cmd/account-server/service/bill/billitem/service.go
> +package billitem
抽空加上包名注释吧

2024-06-16 13:13 UTC, chenjr15 commented on cmd/account-server/service/bill/billitem/service.go
> +package billitem
已添加

2024-06-16 13:14 UTC, chenjr15 commented on cmd/account-server/service/bill/billitem/bill_items.go
> +	_, err := b.client.DataService().Zenlayer.Bill.ListBillItem(kt, billListReq)
已修改

2024-06-16 16:35 UTC, fxdgg approved these changes
LGTM

2024-06-16 16:35 UTC, merged