feature: add bill split task, daily summary task
TencentBlueKing/bk-hcm pull request #884
Opened 2024-06-17 05:16 UTC by abstractmj

2024-06-17 06:36 UTC, chenjr15 commented on cmd/account-server/logics/bill/accountlister.go
> +		},
用 tools.AllExpression  接口

2024-06-17 06:42 UTC, chenjr15 commented on cmd/data-service/service/bill/billitem/update.go
> -		// 全量覆盖更新
这里全量覆盖更新和其他hcm Extension 风格不太一样，之前是会在data service 里面实现Extension 字段按需更新的，所以这行注释保留吧

2024-06-17 06:44 UTC, chenjr15 commented on cmd/account-server/logics/bill/accountlister.go
> +		Filter: tools.ExpressionAnd(),
list 全量 的话，这里命名改成ListAllAccount 吧

2024-06-17 06:44 UTC, chenjr15 commented on cmd/account-server/logics/bill/accountlister.go
> +			},
tools.AllExpression

2024-06-17 06:50 UTC, chenjr15 commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +			mac.RootAccountID, mac.MainAccountID, mac.Vendor, err.Error())
这里没有rid，会不会后面不好看日志，考虑一下增强一下现有的Kit？

2024-06-17 07:33 UTC, chenjr15 commented on cmd/account-server/logics/bill/manager.go
> +	}
没有打日志，错误没有返回，如果确实需要忽略需要补充明确注释

2024-06-17 07:55 UTC, chenjr15 commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +		getInternalKit(), &dsbillapi.BillSummaryMainListReq{
这里是不是可以直接改成：

```go
var expressions = []*filter.AtomRule{
  tools.RuleEqual("root_account_id", mac.RootAccountID),
  tools.RuleEqual("main_account_id", mac.MainAccountID),
  tools.RuleEqual("vendor", mac.Vendor),
  tools.RuleEqual("bill_year", billYear),
  tools.RuleEqual("bill_month", billMonth),
 }

```

2024-06-17 07:57 UTC, chenjr15 commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +	}
需要补一下日志，不然两次调用区分不了

2024-06-17 08:01 UTC, chenjr15 commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +	}
EnsurePullTask 需要日志

2024-06-17 08:17 UTC, liuchenyiwork requested changes

2024-06-17 09:22 UTC, abstractmj commented on cmd/account-server/logics/bill/manager.go
> +	}
bug, 已修复

2024-06-17 09:55 UTC, abstractmj commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +	}
puller里面会打印实际错误，此处打印有点冗余

2024-06-17 10:10 UTC, chenjr15 commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +	}
这里调用了两次，可能会导致混淆

2024-06-17 14:51 UTC, chenjr15 commented on cmd/account-server/logics/bill/mainaccount_controller.go
> +			mac.RootAccountID, mac.MainAccountID, mac.Vendor, err.Error())
记得都补充一下rid哈，其他也看一下

2024-06-17 15:32 UTC, chenjr15 approved these changes

2024-06-18 02:14 UTC, chenjr15 approved these changes

2024-06-18 03:09 UTC, merged