feat: 账单明细表按云厂商、年月分表
TencentBlueKing/bk-hcm pull request #956
Opened 2024-07-16 04:12 UTC by chenjr15

--story=118584294 账单明细分表

2024-07-16 08:34 UTC, fxdgg reviewed
LGTM

2024-07-17 07:04 UTC, breezelxp requested changes

2024-07-17 07:04 UTC, breezelxp commented on pkg/dal/table/bill/billitem.go
> +	yearMonth := abs.BillYear*100 + abs.BillMonth
100，hardcode，没注释，也不通用，调整设计

2024-07-17 09:11 UTC, abstractmj requested changes

2024-07-17 09:28 UTC, chenjr15 commented on pkg/dal/table/bill/billitem.go
> +	if abs == nil {
目前暂无，可以通过create table like 的方式手动复制现有表结构

2024-07-17 09:38 UTC, chenjr15 commented on pkg/dal/table/bill/billitem.go
> +	if abs == nil {
建表可能需要整体支持，目前整个dal都没有相关支持

2024-07-18 02:31 UTC, chenjr15 commented on pkg/dal/table/bill/billitem.go
> +	yearMonth := abs.BillYear*100 + abs.BillMonth
调整到格式化字符串里了

2024-07-18 03:39 UTC, chenjr15 commented on cmd/account-server/logics/bill/summarydaily_controller.go
> +				logs.Infof("summary task of day %d main account %v bill should be create", task.BillDay,
已修改

2024-07-19 05:58 UTC, abstractmj approved these changes
LGTM

2024-07-22 12:03 UTC, fxdgg commented on cmd/account-server/logics/bill/summarydaily_controller.go
> +				logs.Infof("summary task of day %d main account %s bill should be create", task.BillDay,
这里增加一下rid吧

2024-07-23 02:27 UTC, abstractmj submitted a review, later dismissed
LGTM

2024-07-24 06:57 UTC, ZQHcode commented on pkg/dal/dao/orm/orm.go
> +	TableSharding(opt TableShardingOpt, others ...TableShardingOpt) Interface
为什么不直接传一个数组，然后在逻辑里面直接判断长度大于1呢？

2024-07-24 06:57 UTC, ZQHcode commented on pkg/dal/dao/orm/orm.go
> +
和其他不一样，多了个空行，下同

2024-07-24 06:57 UTC, ZQHcode commented on pkg/dal/dao/orm/orm.go
> +	fromTableNameRe = regexp.MustCompile("(?i)\\sfrom\\s+(`?\\w+`?\\.)?`?\\w+`?")
490行直接给值就好了吧，下同

2024-07-24 08:31 UTC, chenjr15 commented on pkg/api/data-service/bill/billitem.go
> +	if r.Filter == nil {
已补充

2024-07-24 08:33 UTC, chenjr15 commented on pkg/dal/dao/bill/billitem.go
> +	shardingOpt := convertShardingOpt(tableName, commonOpt)
shardingOpt 改过去了

2024-07-24 08:33 UTC, chenjr15 commented on pkg/dal/dao/bill/billitem.go
> +		logs.Errorf("insert %s failed, err: %v, shardingOpt:%s, rid: %s", tableName, err, shardingOpt, kt.Rid)
这个不能改，要调用他的String 方法

2024-07-24 08:47 UTC, chenjr15 commented on pkg/dal/dao/orm/option.go
> +func (r *TableSuffixShardingOpt) String() string {
可能会在某一次被扫出来

2024-07-24 08:48 UTC, chenjr15 commented on pkg/dal/dao/orm/orm.go
> +	TableSharding(opt TableShardingOpt, others ...TableShardingOpt) Interface
因为这个如果判断长度，就需要返回错误，就不适合链式调用了

2024-07-24 08:49 UTC, chenjr15 commented on pkg/dal/dao/orm/orm.go
> +	fromTableNameRe = regexp.MustCompile("(?i)\\sfrom\\s+(`?\\w+`?\\.)?`?\\w+`?")
已修改

2024-07-24 11:22 UTC, ZQHcode submitted a review, later dismissed

2024-07-25 04:12 UTC, abstractmj approved these changes

2024-07-25 04:13 UTC, abstractmj approved these changes

2024-07-25 06:14 UTC, merged