GitHub test scr 0802账号管理-创建二级账号支持邮箱输入外部插件化
TencentBlueKing/bk-hcm pull request #994
Opened 2024-08-07 03:01 UTC by Muweij

--story=119008885 【产品需求】账号管理-创建二级账号github支持邮箱输入
# Reviewed, transaction id: 14313

2024-08-07 03:27 UTC, chenjr15 requested changes
pr名字调一下

2024-08-07 03:49 UTC, royalpioneer approved these changes

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +                <Button theme='primary' disabled={!dialogForm.value.code} onClick={() => handleConfirm()}>
onClick-handler 这里不涉及到传参，可以直接将 handleConfirm 赋值给 onClick

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +                <Button class='dialog-cancel' onClick={() => handleClose()}>
同上

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +    const formModelRef = ref();
这里的状态和下面的 handler 分离太严重，虽然使用的是组合式API，但这里却体现为选择式API的风格。

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +    const formModelRef = ref();
不方便 review，也不方便后期维护。

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +      if (timer) {
timer其实可以不用判断是否为空，直接 clearInterval 就行，没有的话他也不会出问题。
开启定时器之前都可以默认清一下定时器，保证不会出错。

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +                      <FormItem label='账号邮箱' required property='email'>
这个 FormItem 里面的内容是不是可以单独抽离成一个业务组件？我看了一下，内容还挺多的。

2024-08-09 02:32 UTC, coder-cwc commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +                      <FormItem label='账号邮箱' required property='email'>
抽离成组件后，可以通过 expose 进行暴露。然后父组件中使用 ref 来进行数据收集。

2024-08-09 02:48 UTC, yangyy commented on front/src/plugin-handler/create-account.ts
> +import { ref } from 'vue';
`create-account`范围太在不够准确，实际上这个plugin是创建账号中针对邮箱后缀的处理，重命名为 `create-account-mail-suffix`

2024-08-09 02:49 UTC, yangyy commented on front/src/plugin-handler/create-account.ts
> +  isuffix: '' as any,
`isuffix` => `suffixText`

2024-08-09 02:56 UTC, yangyy commented on front/src/plugin-handler/create-account.ts
> +  isMailRules: ref(false),
isMailRules => isMailValid

2024-08-09 02:57 UTC, yangyy commented on front/src/views/bill/account/create-account/create-second-account/constants.ts
> +  SecondaryAccount: 'SecondAccountApplication',
key SecondaryAccount 最好也是 SecondAccountApplication

2024-08-09 03:09 UTC, yangyy commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +    const VerificationResults = ref('Not verified');
VerificationResults 命名和使用字符定义验证状态都不直观，所有的这些变量都是在为“邮箱校验”添加的，但放在整个功能模块的语境下，就显示不够具体，比如 isComplete 放在整个语境下，是什么的完成不够清晰。就 VerificationResults 这个，emailCodeVerfiyResult = ref(null) true / fasle 三个状态。
此外这里，1. 变量收敛或者命名加上邮箱检验语义；2. 考虑把countdown写成一个公共的hook

2024-08-09 03:10 UTC, yangyy commented on front/src/views/bill/account/create-account/create-second-account/index.tsx
> +          VerifyCode: dialogForm.value.code,
`VerifyCode`确定是这个参数名？

2024-08-09 08:23 UTC, closed without merging